### ISSUE TITLE
[EXPIRED] Pure JS implementation

### ISSUE THREAD

**Issue by sergeevabc** [chrisumbel/thirty-two#3]
Dear Chris,
for the rest of us, who neither use nor plan to install Node, could you be so kind and improve current implementation of Base32 to overcome error `Uncaught ReferenceError: Buffer is not defined`?

**Comment by mikepb** [comment]
There are a few Base-32 implementations for pure JavaScript out there, here's mine:
https://github.com/mikepb/base32.js

**Comment by coolaj86** [comment]
I like how small this library is (though I completely agree that Crockford's Base32 is less confusing (L vs l vs I vs i is much worse than g vs 9.

I got it working with just a few one-liner changes and I've published it for the browser as part of https://github.com/coolaj86/unibabel-js

This single file can be also be used <https://github.com/coolaj86/unibabel-js/blob/master/unibabel.b32.js>.

* `window.base32ToBuffer(b32string)`
* `window.bufferToBase32(array)`
